config/routes.rb
Rails.application.routes.draw do
  # resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'welcome#index'
  get   '/contact',       to: 'contacts#new',       as: 'new_contact'
  # get   '/contacts',      to: 'contacts#index'
  # get   '/contacts/new',  to: 'contacts#new',     as: 'new_contact'
  post  '/contacts',       to: 'contacts#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  # def index
  #   @contacts = Contact.all
  # end

  # GET /contacts/1
  # GET /contacts/1.json
  # def show
  # end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  # def edit
  # end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        ContactMailer.contact_email(@contact).deliver
        format.html { redirect_to new_contact_path, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  # def update
  #   respond_to do |format|
  #     if @contact.update(contact_params)
  #       format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @contact }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @contact.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  # def destroy
  #   @contact.destroy
  #   respond_to do |format|
  #     format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_contact
    #   @contact = Contact.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :company, :phone, :email, :body, :robot)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <a id="contact-form"></a>
  <div class="fh5co-contact animate-box">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 col-md-push-2 animate-box">
          <h2>Contact Us</h2>
          <p>Drop us a line if you are interested in learning more or think you would like to work with us.</p><br><br>

        </div>
        <div class="col-md-3">
          <h3>Contact Info.</h3>
          <ul class="contact-info">
            <li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>&nbsp;<a href="tel:+19893213806">+ 989 321 3806</a></li>
            <li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;<a href="mailto:bramanga@gmail.com">bramanga@gmail.com</a></li>
            <li><span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp;<a href="http://distributedpixel.com">www.distributedpixel.com</a></li>
          </ul>
        </div>
        <div class="col-md-8 col-md-push-1 col-sm-12 col-sm-push-0 col-xs-12 col-xs-push-0">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.text_field :name, :class => "form-control", :type => "text", :placeholder => "Name", :required => true %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.text_field :company, :class => "form-control", :type => "text", :placeholder => "Company" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.text_field :phone, :class => "form-control", :type => "text", :placeholder => "Phone" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.text_field :email, :class => "form-control", :type => "text", :placeholder => "Email", :required => true %>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <%= f.text_area :body, :class => "form-control", :type => "textarea", :placeholder => "Message", :required => true %>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <%= f.submit "Send Message" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Body</th>
      <th>Robot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.company %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= contact.body %></td>
        <td><%= contact.robot %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<div class="image-splash contact-splash">
  <h1>
    Get in touch <br />with us.<br />
    <a href="/contact#contact-form" class="btn btn-primary btn-outline btn-lg">Contact Us</a>
  <h1>
</div>

<%= render 'form', contact: @contact %>

<!-- <%= link_to 'Back', contacts_path %> -->

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contact.company %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @contact.body %>
</p>

<p>
  <strong>Robot:</strong>
  <%= @contact.robot %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Distributed Pixel LLC</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="fh5co-page">
    <header id="fh5co-header" role="banner">
      <div class="container">
        <div class="header-inner">
          <h1><a href="/">Distributed Pixel LLC</a></h1>
          <nav role="navigation">
            <ul>
              <li><a href="/">Home</a></li>
              <!-- <li><a href="work.html">Work</a></li>
              <li><a href="services.html">Services</a></li>
              <li><a href="pricing.html">Pricing</a></li>
              <li><a href="about.html">About</a></li> -->
              <li><a href="/contact">Contact</a></li>
              <li class="cta"><a href="/#our-services">Learn More</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
    </div>
    <%= yield %>
    <footer id="fh5co-footer" role="contentinfo">

    <div class="container">
      <div class="col-md-3 col-sm-12 col-sm-push-0 col-xs-12 col-xs-push-0">
        <h3>About Us</h3>
        <p>Greg Braman is a Freelance Web Developer that loves providing custom web solutions to serve his clients needs. </p>
        <p><a href="/contact#contact-form" class="btn btn-primary btn-outline with-arrow btn-sm">Contact Us <i class="icon-arrow-right"></i></a></p>
      </div>
      <div class="col-md-6 col-md-push-1 col-sm-12 col-sm-push-0 col-xs-12 col-xs-push-0">
        <!-- <h3>Our Services</h3>
        <ul class="float">
          <li><a href="#">Web Design</a></li>
          <li><a href="#">Branding &amp; Identity</a></li>
          <li><a href="#">Free HTML5</a></li>
          <li><a href="#">HandCrafted Templates</a></li>
        </ul> -->
        <!-- <ul class="float">
          <li><a href="#">Free Bootstrap Template</a></li>
          <li><a href="#">Free HTML5 Template</a></li>
          <li><a href="#">Free HTML5 &amp; CSS3 Template</a></li>
          <li><a href="#">HandCrafted Templates</a></li>
        </ul> -->

      </div>

      <div class="col-md-2 col-md-push-1 col-sm-12 col-sm-push-0 col-xs-12 col-xs-push-0">
        <!-- <h3>Follow Us</h3>
        <ul class="fh5co-social">
          <li><a href="#"><i class="icon-twitter"></i></a></li>
          <li><a href="#"><i class="icon-facebook"></i></a></li>
          <li><a href="#"><i class="icon-google-plus"></i></a></li>
          <li><a href="#"><i class="icon-instagram"></i></a></li>
        </ul> -->
      </div>


      <div class="col-md-12 fh5co-copyright text-center">
        <p>&copy; <%= Time.now.year || 2016 %> Distributed Pixel LLC. All Rights Reserved.
<!--                    <span>Designed with <i class="icon-heart"></i> by <a href="http://freehtml5.co/" target="_blank">FreeHTML5.co</a> Demo Images by <a href="http://unsplash.com/" target="_blank">Unsplash</a></span>-->
                </p>
      </div>

    </div>
  </footer>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="image-splash home-splash">
  <h1>
    Take your business <br />to the next level.<br />
    <a href="#our-services" class="btn btn-primary btn-outline btn-lg">Learn More</a>
  <h1>
</div>
<a id="our-services"></a>
<div id="fh5co-services-section">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3 text-center fh5co-heading animate-box">
          <h2>Our Services</h2>
          <p>Check out the services we have to offer.<br />If you would like to know more, feel free to <a href="/contact#contact-form">Contact Us</a>.</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 animate-box">
          <div class="services">
            <i class="icon-server"></i>
            <div class="desc">
              <h3>Web Development</h3>
              <p>Need a new website or updated content? Consider our Web Development services complete with Search Engine Optimization and Page Rank upgrades.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4 animate-box">
          <div class="services">
            <i class="icon-pie-chart"></i>
            <div class="desc">
              <h3>Custom Web Applications</h3>
              <p>Take your business to the next level with a custom built web application. Provide your clients with exactly what they need to be successful.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4 animate-box">
          <div class="services">
            <i class="icon-laptop"></i>
            <div class="desc">
              <h3>Managed IT</h3>
              <p>We provide Managed IT solutions for small and home businesses. Take your business to the next level with our affordable Managed IT services.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>